ojs_data_export_issue:
  path:     /
  defaults: { _controller: "OjsExportBundle:IssueExport:index" }

ojs_data_export_single_issue_json:
  path:     /{id}/json
  defaults: { _controller: "OjsExportBundle:IssueExport:singleIssueJson" }

ojs_data_export_single_issue_xml:
  path:     /{id}/xml
  defaults: { _controller: "OjsExportBundle:IssueExport:singleIssueXml" }
