ojs_data_export_issue:
  path:     /
  defaults: { _controller: "OjsExportBundle:IssueExport:index" }

ojs_data_export_issue_json:
    path:     /json
    defaults: { _controller: "OjsExportBundle:IssueExport:json" }

ojs_data_export_issue_xml:
    path:     /xml
    defaults: { _controller: "OjsExportBundle:IssueExport:xml" }
