ojs_data_export_user:
  path:     /
  defaults: { _controller: "OjsExportBundle:UserExport:index" }

ojs_data_export_single_user_json:
  path:     /{id}/json
  defaults: { _controller: "OjsExportBundle:UserExport:singleUserJson" }

ojs_data_export_single_user_xml:
  path:     /{id}/xml
  defaults: { _controller: "OjsExportBundle:UserExport:singleUserXml" }
